version: "3.8"
services:
  db:
    image: postgres:alpine
    volumes:
      - "dbdata:/var/lib/postgres/data"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: db123
      POSTGRES_DB: poll_app
volumes:
  dbdata:
